print('Hello', end=' ')
print(10, end=' ')
print(2.1, end=' ')
print(False)
print(1, end='_разделитель_')
print(2, end='_разделитель_')
print(3, end='_разделитель_')
print(4)
print(1, 2, 3, end= ' ', sep='*')
print(4, 5, sep='*', end=' :-)')